services:
  app:
    build: .
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
